### ISSUE TITLE
A General server structure is needed

### ISSUE THREAD

**Issue by Pedram-Mirelmi** [Pedram-Mirelmi/CN_CHomeworks1#1]
Seems we need a general structure for all three assignments. so first let's develop a simple yet extensible framework for it.

**Comment by Pedram-Mirelmi** [comment]
Boost.Asio seems good for an asynchronous approach. 
I'll draw a UML diagram for it.

**Comment by AliRanjbari** [comment]
Ok then :)

**Comment by Pedram-Mirelmi** [comment]
I just finished this one. 
![AsioAsyncServerLib](https://user-images.githubusercontent.com/82533743/206528047-2c84fefd-5a50-42fe-b11e-7e960ad0a29f.png)

what do you think?

**Comment by AliRanjbari** [comment]
You have to explain it to me. but is seems all right.
