### ISSUE TITLE
FTP server

### ISSUE THREAD

**Issue by AliRanjbari** [Pedram-Mirelmi/CN_CHomeworks1#2]
Hi,
We Need a FTP server using the framework that we just developed.
And also a client interface for communicating with the server.
All the message that  needed between server and client are as bellow:
* username(client => server)
* pass (client => server)
* retr or donwload (client => server)
* upload(clietn => server)
* help (client => server)
* quite (client => server)
* short response (server => client)
* file content (server => client)
* help content (server => client)

**Comment by Pedram-Mirelmi** [comment]
Good!

So the scenario is that 

1. First client sends its username with `username` message
2. Server either accepts it and goes to next step or sends a `short response` and says that the username is not acceptable
3. If the username is Okay, then server sends a `short response` containing the appropriate code and waits for client to send password
4. Client sends its password with a `password` message.
5. Server responses with a `short response` letting client know that the password was right or not. and goes to step 4 or next step which we call it **idle state**
6. In this step (or state) server has authenticated the client and waits for requests to serve the client. 
7. if client wants a file sends a `retr` or `download` message to server. In response, if the file doesn't exist, server sends a `short response`, but if it existed server sends a `short response` and then a `file content`.
8. if client wants to upload a file its just the same. server will let client know if it has the permission to upload files by a `short response`
9. if clients wants help it'll sends a `help` message and server responses with a `help content` message
10. and finally if clients want to close the connection sends a `quit` message and server responses with a `short response`

**Comment by Pedram-Mirelmi** [comment]
I added the following short response numbers in addition to those in the PDF:

224: server states that file is available and will send it right away
225: server states that the client the permission to upload file

403: server states that user doesn't have the permission to upload file
